version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/term/
permissions:
  - object: /home/ec2-user/term
    pattern: "**"
    owner: ec2-user
    mode: 777
    type:
      - directory
hooks:
  AfterInstall:
    - location: scripts/install.sh
      runas: ec2-user
      timeout: 300
  ApplicationStart:
    - location: scripts/start.sh
      runas: ec2-user
      timeout: 60