version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/term/
hooks:
  AfterInstall:
    - location: scripts/install.sh
      runas: ec2-user
      timeout: 300
  ApplicationStart:
    - location: scripts/start.sh
      runas: ec2-user
      timeout: 60